### ISSUE TITLE
Use Minio for s3 integration tests in CI

### ISSUE THREAD

**Issue by Daenyth** [lendup/fs2-blobstore#18]
I'm willing to send this in as a PR. How do you want it? One travis build that does the current behavior + s3 tests?

I think the alternate approach might be to move the integration tests to `src/e2e` so they can be invoked separately more easily, and have two travis builds, one for test and one for e2e - the downside to this approach is that it makes coverage collection more complex.

**Comment by rolandomanrique** [comment]
@Daenyth sorry for how long it took to respond to this. Thanks for suggesting minio, it was super easy to set up with docker compose.

In the end I chose to remove the `@IntegrationTest` annotation from S3 and SFTP tests and maintain current builds set up, given the nature of the project, it is critical to exercise S3 and SFTP clients code on every test we run.

We still have `BoxStore` tests annotated as "integration" because we have not found a box.com compatible docker image. We are still running those manually before publishing artifacts.

**Comment by rolandomanrique** [comment]
@Daenyth fixed SFTP container issue by telling amotz/sftp container to create root tests dir inside the container per https://github.com/atmoz/sftp/issues/37#issuecomment-239466899

Figured this out thanks to travis support enabling debug mode in the project. Thanks again for the help.

**Comment by Daenyth** [comment]
Glad I could help! I'm excited for the improvement to the project :)
